### ISSUE TITLE
Add configurable placeholders in flexmodel xml

### ISSUE THREAD

**Issue by deborahvandervegt** [FlexModel/FlexModel#9]

**Comment by niels-nijens** [comment]
It's possible to add a placeholder to a field within the form_defaults node.

``` xml
<field name='foo' label='Foo'>
    <form_defaults>
        <notices placeholder='Placeholder for Foo'/>
    </form_defaults>
</field>
```

Though, I think it would be better to move it to the form_defaults node entirely...

**Comment by deborahvandervegt** [comment]
Hi Niels,

Is there still work to do to complete this issue?
